/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    AgentRegistry: {
      address: "0x2bcd5637fc34ecc488eba4ba209dacad05cf0d76",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "actionRouter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "agentCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "agentOf",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct AgentRegistry.Agent",
              components: [
                {
                  name: "controller",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "operator",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "treasury",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "metadataURI",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "active",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "registeredAt",
                  type: "uint64",
                  internalType: "uint64",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "authorizeSpend",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "isAuthorizedOperator",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "policyOf",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct AgentRegistry.SpendPolicy",
              components: [
                {
                  name: "maxPerAction",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "maxPerEpoch",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "epochDuration",
                  type: "uint64",
                  internalType: "uint64",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "registerAgent",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
            {
              name: "treasury",
              type: "address",
              internalType: "address",
            },
            {
              name: "metadataURI",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setActionRouter",
          inputs: [
            {
              name: "router",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setActive",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setMetadataURI",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "metadataURI",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setOperator",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setSpendPolicy",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "maxPerAction",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxPerEpoch",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "epochDuration",
              type: "uint64",
              internalType: "uint64",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setTreasury",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "treasury",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "spentThisEpoch",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferControl",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "newController",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "ActionRouterChanged",
          inputs: [
            {
              name: "previousRouter",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newRouter",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ActiveChanged",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "active",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "AgentRegistered",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "controller",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ControllerTransferred",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "previousController",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newController",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MetadataChanged",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "metadataURI",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OperatorChanged",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "previousOperator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOperator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SpendPolicyChanged",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "maxPerAction",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "maxPerEpoch",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "epochDuration",
              type: "uint64",
              indexed: false,
              internalType: "uint64",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SpendRecorded",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "epochTotal",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TreasuryChanged",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "previousTreasury",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newTreasury",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AgentRegistry__AgentInactive",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "AgentRegistry__ExceedsPerAction",
          inputs: [
            {
              name: "requested",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "allowed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "AgentRegistry__ExceedsPerEpoch",
          inputs: [
            {
              name: "requested",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "remaining",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "AgentRegistry__InvalidPolicy",
          inputs: [],
        },
        {
          type: "error",
          name: "AgentRegistry__NoPolicy",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "AgentRegistry__NotController",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "caller",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "AgentRegistry__NotOperator",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "caller",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "AgentRegistry__NotRouter",
          inputs: [
            {
              name: "caller",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "AgentRegistry__UnknownAgent",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "AgentRegistry__ZeroAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40893517,
    },
    ActionRouter: {
      address: "0x50f1ae91073add5dc4f833c95ce8230872ce4f88",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
            {
              name: "registryAddress",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "actionCount",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "count",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "associate",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "associateMany",
          inputs: [
            {
              name: "tokens",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "disableAdapter",
          inputs: [
            {
              name: "adapter",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "enableAdapter",
          inputs: [
            {
              name: "adapter",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "executeAction",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "adapter",
              type: "address",
              internalType: "address",
            },
            {
              name: "request",
              type: "tuple",
              internalType: "struct IAgentAction.ActionRequest",
              components: [
                {
                  name: "kind",
                  type: "uint8",
                  internalType: "enum IAgentAction.ActionKind",
                },
                {
                  name: "assetIn",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amountIn",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "assetOut",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "minAmountOut",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "protocolData",
                  type: "bytes",
                  internalType: "bytes",
                },
              ],
            },
          ],
          outputs: [
            {
              name: "amountOut",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "isAdapterEnabled",
          inputs: [
            {
              name: "adapter",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "enabled",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "registry",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract AgentRegistry",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "ActionExecuted",
          inputs: [
            {
              name: "agentId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "protocolId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "kind",
              type: "uint8",
              indexed: true,
              internalType: "enum IAgentAction.ActionKind",
            },
            {
              name: "operator",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "assetIn",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "amountIn",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "assetOut",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "amountOut",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "protocolRef",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "sequence",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "AdapterDisabled",
          inputs: [
            {
              name: "adapter",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "AdapterEnabled",
          inputs: [
            {
              name: "adapter",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "protocolId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TokenAssociated",
          inputs: [
            {
              name: "token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ActionRouter__AdapterNotEnabled",
          inputs: [
            {
              name: "adapter",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ActionRouter__AdapterRejectsAction",
          inputs: [
            {
              name: "adapter",
              type: "address",
              internalType: "address",
            },
            {
              name: "kind",
              type: "uint8",
              internalType: "enum IAgentAction.ActionKind",
            },
          ],
        },
        {
          type: "error",
          name: "ActionRouter__InsufficientOutput",
          inputs: [
            {
              name: "received",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "minimum",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ActionRouter__SameAssetRequiresNoSweep",
          inputs: [],
        },
        {
          type: "error",
          name: "ActionRouter__ZeroAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "ActionRouter__ZeroAmount",
          inputs: [],
        },
        {
          type: "error",
          name: "HtsAssociatable__AssociationFailed",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "responseCode",
              type: "int64",
              internalType: "int64",
            },
          ],
        },
        {
          type: "error",
          name: "HtsAssociatable__ZeroAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40893520,
    },
    SaucerSwapAdapter: {
      address: "0x34dc78d33a76e5ac6c5546c6241f903c66fca506",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
            {
              name: "swapRouterAddress",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "associate",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "associateMany",
          inputs: [
            {
              name: "tokens",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "execute",
          inputs: [
            {
              name: "request",
              type: "tuple",
              internalType: "struct IAgentAction.ActionRequest",
              components: [
                {
                  name: "kind",
                  type: "uint8",
                  internalType: "enum IAgentAction.ActionKind",
                },
                {
                  name: "assetIn",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amountIn",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "assetOut",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "minAmountOut",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "protocolData",
                  type: "bytes",
                  internalType: "bytes",
                },
              ],
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct IAgentAction.ActionResult",
              components: [
                {
                  name: "assetOut",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amountOut",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "protocolRef",
                  type: "bytes32",
                  internalType: "bytes32",
                },
              ],
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "protocolId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "supportsAction",
          inputs: [
            {
              name: "kind",
              type: "uint8",
              internalType: "enum IAgentAction.ActionKind",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "swapRouter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISaucerSwapV2Router",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TokenAssociated",
          inputs: [
            {
              name: "token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "HtsAssociatable__AssociationFailed",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "responseCode",
              type: "int64",
              internalType: "int64",
            },
          ],
        },
        {
          type: "error",
          name: "HtsAssociatable__ZeroAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "IAgentAction__InsufficientOutput",
          inputs: [
            {
              name: "received",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "minimum",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "IAgentAction__UnsupportedAction",
          inputs: [
            {
              name: "kind",
              type: "uint8",
              internalType: "enum IAgentAction.ActionKind",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "SaucerSwapAdapter__MalformedPath",
          inputs: [
            {
              name: "length",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "SaucerSwapAdapter__PathInputMismatch",
          inputs: [
            {
              name: "pathToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "requestToken",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "SaucerSwapAdapter__PathOutputMismatch",
          inputs: [
            {
              name: "pathToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "requestToken",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "SaucerSwapAdapter__ZeroAddress",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40893525,
    },
    BonzoAdapter: {
      address: "0x5b89b6ba0bb905f97bb0da0f827e20d930f5abc0",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
            {
              name: "lendingPoolAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "dataProviderAddress",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "associate",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "associateMany",
          inputs: [
            {
              name: "tokens",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "dataProvider",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IBonzoDataProvider",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "execute",
          inputs: [
            {
              name: "request",
              type: "tuple",
              internalType: "struct IAgentAction.ActionRequest",
              components: [
                {
                  name: "kind",
                  type: "uint8",
                  internalType: "enum IAgentAction.ActionKind",
                },
                {
                  name: "assetIn",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amountIn",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "assetOut",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "minAmountOut",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "protocolData",
                  type: "bytes",
                  internalType: "bytes",
                },
              ],
            },
            {
              name: "onBehalfOf",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct IAgentAction.ActionResult",
              components: [
                {
                  name: "assetOut",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amountOut",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "protocolRef",
                  type: "bytes32",
                  internalType: "bytes32",
                },
              ],
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "lendingPool",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IBonzoLendingPool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "protocolId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "supportsAction",
          inputs: [
            {
              name: "kind",
              type: "uint8",
              internalType: "enum IAgentAction.ActionKind",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TokenAssociated",
          inputs: [
            {
              name: "token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "BonzoAdapter__AssetInIsNotTheAToken",
          inputs: [
            {
              name: "declared",
              type: "address",
              internalType: "address",
            },
            {
              name: "expected",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "BonzoAdapter__AssetOutIsNotTheAToken",
          inputs: [
            {
              name: "declared",
              type: "address",
              internalType: "address",
            },
            {
              name: "expected",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "BonzoAdapter__InvalidRateMode",
          inputs: [
            {
              name: "rateMode",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "BonzoAdapter__RepayAssetsMustMatch",
          inputs: [
            {
              name: "assetIn",
              type: "address",
              internalType: "address",
            },
            {
              name: "assetOut",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "BonzoAdapter__ReserveNotListed",
          inputs: [
            {
              name: "asset",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "BonzoAdapter__ZeroAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "HtsAssociatable__AssociationFailed",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "responseCode",
              type: "int64",
              internalType: "int64",
            },
          ],
        },
        {
          type: "error",
          name: "HtsAssociatable__ZeroAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "IAgentAction__InsufficientOutput",
          inputs: [
            {
              name: "received",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "minimum",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "IAgentAction__UnsupportedAction",
          inputs: [
            {
              name: "kind",
              type: "uint8",
              internalType: "enum IAgentAction.ActionKind",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40893528,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
